import { StatusLabel } from "@/components/internal/status-label";
import { assignRoleAction, blockAccountAction, removeRoleAction, restoreAccountAction } from "@/app/admin/users/actions";
import { assignableRoles } from "@/lib/admin/data";
import type { Role } from "@/types";

const buttonClass = "min-h-11 rounded-xl border border-white/15 px-4 py-2 text-sm font-extrabold text-white hover:border-cyan-300/40 hover:bg-white/[0.05]";

function Confirmation({ id }: { id: string }) {
  return <label htmlFor={id} className="flex min-h-11 items-start gap-3 rounded-xl border border-white/10 p-3 text-sm leading-5 text-zinc-300"><input id={id} name="confirmation" value="confirmed" type="checkbox" required className="mt-1 size-4 accent-cyan-300" /><span>I confirm this privileged change for the account shown above.</span></label>;
}

export function UserManagementForms({ userId, roles, blocked }: { userId: string; roles: Role[]; blocked: boolean }) {
  return <div className="grid gap-5 xl:grid-cols-2">
    <section aria-labelledby="role-management-title" className="rounded-2xl border border-white/10 bg-[#12151c] p-5 sm:p-6"><h2 id="role-management-title" className="font-display text-2xl font-bold text-white">Role management</h2><p className="mt-2 text-sm leading-6 text-zinc-400">A subscriber role is only an authorization label. It never activates a subscription, payment, or member entitlement.</p><div className="mt-5 grid gap-4">{assignableRoles.map((role) => { const assigned = roles.includes(role); const action = assigned ? removeRoleAction.bind(null, userId, role) : assignRoleAction.bind(null, userId, role); const confirmationId = `confirm-role-${role}`; return <form action={action} key={role} className="rounded-xl border border-white/10 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><StatusLabel tone={assigned ? "info" : "neutral"}>{role.replace("_", " ")}</StatusLabel><span className="text-xs font-bold text-zinc-500">{assigned ? "Assigned" : "Not assigned"}</span></div><div className="mt-3"><Confirmation id={confirmationId} /></div><button type="submit" className={`${buttonClass} mt-3`}>{assigned ? `Remove ${role.replace("_", " ")}` : `Assign ${role.replace("_", " ")}`}</button></form>; })}</div></section>
    <section aria-labelledby="restriction-management-title" className="rounded-2xl border border-white/10 bg-[#12151c] p-5 sm:p-6"><h2 id="restriction-management-title" className="font-display text-2xl font-bold text-white">Account access</h2><p className="mt-2 text-sm leading-6 text-zinc-400">Application-level restrictions deny protected areas without deleting the Auth user or changing credentials. The internal reason is never shown to the account holder.</p>{blocked ? <form action={restoreAccountAction.bind(null, userId)} className="mt-5 space-y-3"><Confirmation id="confirm-restore" /><button type="submit" className={buttonClass}>Restore account access</button></form> : <form action={blockAccountAction.bind(null, userId)} className="mt-5 space-y-3"><div><label htmlFor="block-reason" className="text-sm font-bold text-zinc-200">Internal reason</label><p id="block-reason-help" className="mt-1 text-xs leading-5 text-zinc-500">Required, 3–500 characters. Stored privately and excluded from audit records.</p></div><textarea id="block-reason" name="reason" minLength={3} maxLength={500} required rows={4} aria-describedby="block-reason-help" className="w-full resize-y rounded-xl border border-white/15 bg-black/20 p-3 text-white outline-none focus:border-rose-300 focus:ring-2 focus:ring-rose-300/20" /><Confirmation id="confirm-block" /><button type="submit" className="min-h-11 rounded-xl bg-rose-500 px-4 py-2 text-sm font-extrabold text-white hover:bg-rose-400">Block account access</button></form>}</section>
  </div>;
}
