import type { Metadata } from "next";

import { LegalPage, LegalSection } from "@/components/legal/legal-page";
import { getPublicLegalConfig } from "@/lib/site/legal-config";

export const metadata: Metadata = { title: "Privacy policy", robots: { index: false, follow: true } };
export const dynamic = "force-dynamic";

export default function PrivacyPage() {
  const legal = getPublicLegalConfig();

  return <LegalPage eyebrow="Data protection" title="Privacy policy" description="International pre-launch privacy notice based on the processing currently implemented. Technical review: 7 August 2026." incomplete={!legal.complete}>
    <LegalSection title="Controller">
      {legal.complete ? <><p><strong>{legal.operatorName}</strong></p><p>{legal.streetAddress}, {legal.postalLocality}, {legal.country}</p><p>Email: <a href={`mailto:${legal.supportEmail}`}>{legal.supportEmail}</a></p></> : <p>The controller&apos;s verified identity, address, telephone number, and monitored privacy contact must be configured before launch.</p>}
    </LegalSection>
    <LegalSection title="Applicable privacy frameworks"><p>The final controller is expected to operate from Thailand, so the Thailand Personal Data Protection Act B.E. 2562 (2019) must be assessed and followed where applicable. The EU General Data Protection Regulation may also apply to relevant processing when the service offers goods or services to people in the European Economic Area or monitors their behaviour there. Other local privacy laws may apply based on a user&apos;s location and the final markets served. This draft does not claim that one country&apos;s law applies exclusively.</p></LegalSection>
    <LegalSection title="Hosting and security logs"><p>The website is expected to be hosted on Vercel. Requests disclose network and request information such as IP address, time, requested URL, user agent, and technical error or security events where needed to deliver, protect and troubleshoot the service. Production regions, log retention and contractual terms must be verified before launch.</p></LegalSection>
    <LegalSection title="Accounts and authentication"><p>Supabase provides authentication and database services. Depending on account use, the service processes email address, a provider-generated user identifier, display name, authentication timestamps, account status, roles, subscription and age-verification status, and data-minimized security or administration audit events. Passwords and authentication credentials are handled by Supabase and are not displayed to website administrators.</p></LegalSection>
    <LegalSection title="Necessary cookies and local storage"><p>Supabase session cookies keep signed-in users authenticated. The short-lived <code>bj-password-recovery</code> cookie protects password recovery and expires after ten minutes. The Pattaya Guide stores selected favourite identifiers locally in the browser only after the visitor uses that function. No advertising or analytics cookies are configured in the current application.</p></LegalSection>
    <LegalSection title="Payments, email, and age verification"><p>Stripe billing, Resend production email, and professional age verification are not live. Before activation, this notice must be updated with the actual provider roles, data categories, purposes, legal grounds, locations and retention. The planned Stripe flow uses Stripe-hosted checkout and account-management pages; full card details must not be stored by this website. Auth email delivery will use the verified mail domain only after production setup.</p></LegalSection>
    <LegalSection title="Maps, external media, and links"><p>The Pattaya Guide loads map resources from Mapbox. Video pages may request thumbnails or, after user interaction, player content from YouTube. Subscriber posts can contain YouTube or Vimeo players. Opening Rumble, Kick, social-media, or other external links transfers the visitor to that provider. These providers receive normal request information under their own policies.</p></LegalSection>
    <LegalSection title="Purposes and lawful grounds"><p>Depending on the applicable law, account and requested-service processing may be necessary to enter into or perform a contract. Security, abuse prevention, reliable operation and data-minimized audit records may rely on legitimate interests or another permitted ground after documented assessment. Statutory records may be required by law. Optional processing that requires consent must remain disabled until a valid, specific and withdrawable choice is available. Final lawful grounds must be reviewed for Thailand and each intentionally served market.</p></LegalSection>
    <LegalSection title="Retention"><p>Account data is retained while the account is active and then deleted or restricted when no longer required, subject to security, dispute, tax, and statutory retention needs. Provider logs and backups follow reviewed provider settings. A final retention schedule must be approved before launch; raw authentication links and passwords must never be retained in application logs.</p></LegalSection>
    <LegalSection title="Recipients and international transfers"><p>Current or planned technical recipients can include Vercel, Supabase, Mapbox, Stripe and Resend. YouTube or Vimeo become recipients when their content is requested; other external sites receive data only when a visitor opens them. Provider entities, processing regions, sub-processors, data-processing agreements and any transfer safeguards required under the Thailand PDPA, GDPR or other applicable law must be verified against the actual production accounts before launch.</p></LegalSection>
    <LegalSection title="Your privacy rights"><p>Rights depend on the law that applies to the request. They may include access, correction, deletion, restriction or objection, withdrawal of consent, portability, and a complaint to the competent privacy authority. Requests should use the published privacy contact. The controller may need limited information to verify identity and protect the account, and may retain data where lawfully required.</p></LegalSection>
    <LegalSection title="Children and age-restricted areas"><p>The public website is not intended to collect children&apos;s data. Member areas may contain age-restricted nightlife content and are intended only for users who satisfy the published minimum age and any required verification. The final age threshold, verification provider and handling of verification data require jurisdiction-specific review before paid access launches.</p></LegalSection>
    <LegalSection title="Policy changes"><p>This notice will be updated when providers, purposes, legal bases, retention, or contact details change. Material changes affecting registered users should be communicated through an appropriate account or email notice.</p></LegalSection>
  </LegalPage>;
}
