import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";

import { StatusLabel } from "@/components/internal/status-label";
import { loadRealAccountState } from "@/lib/auth/access-state";
import { signOutAction } from "./actions";

export const metadata: Metadata = { title: "Account" };

export default async function AccountPage() {
  const state = await loadRealAccountState();
  if (!state.user) redirect("/login?next=/account");
  const createdAt = state.createdAt ? new Intl.DateTimeFormat("en", { dateStyle: "long", timeZone: "UTC" }).format(new Date(state.createdAt)) : "Unavailable";
  return <main id="main-content" className="page-shell flex-1 py-12 sm:py-16 lg:py-20"><div className="flex flex-wrap items-start justify-between gap-5 border-b border-white/10 pb-8"><div><p className="eyebrow text-cyan-300">Validated Supabase account</p><h1 className="font-display mt-3 text-5xl font-bold tracking-tight text-white sm:text-6xl">Account summary</h1><p className="mt-4 max-w-2xl leading-7 text-zinc-400">Safe identity and access state loaded on the server through the authenticated session and RLS-protected records.</p></div><form action={signOutAction}><button type="submit" className="min-h-11 rounded-full border border-white/15 px-5 text-sm font-extrabold text-white hover:bg-white/[0.05]">Sign out</button></form></div>
    {state.accessLoadFailed ? <p role="alert" className="mt-7 rounded-xl border border-rose-300/20 bg-rose-300/[0.06] p-4 text-sm text-rose-100">Some account state could not be loaded. Access has been denied conservatively.</p> : null}
    <section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3" aria-label="Account details"><article className="rounded-2xl border border-white/10 bg-[var(--surface)] p-5"><p className="text-xs font-extrabold uppercase tracking-wider text-zinc-600">Email</p><p className="mt-3 break-all font-bold text-white">{state.user.email ?? "Unavailable"}</p></article><article className="rounded-2xl border border-white/10 bg-[var(--surface)] p-5"><p className="text-xs font-extrabold uppercase tracking-wider text-zinc-600">Display name</p><p className="mt-3 font-bold text-white">{state.displayName ?? "Not set"}</p></article><article className="rounded-2xl border border-white/10 bg-[var(--surface)] p-5"><p className="text-xs font-extrabold uppercase tracking-wider text-zinc-600">Created</p><p className="mt-3 font-bold text-white">{createdAt}</p></article><article className="rounded-2xl border border-white/10 bg-[var(--surface)] p-5"><p className="text-xs font-extrabold uppercase tracking-wider text-zinc-600">Account status</p><div className="mt-3"><StatusLabel tone={state.accountBlocked ? "danger" : "positive"}>{state.accountBlocked ? "Access unavailable" : "Active"}</StatusLabel></div></article><article className="rounded-2xl border border-white/10 bg-[var(--surface)] p-5"><p className="text-xs font-extrabold uppercase tracking-wider text-zinc-600">Roles</p><div className="mt-3 flex flex-wrap gap-2">{state.roles.length ? state.roles.map((role) => <StatusLabel key={role} tone="info">{role.replace("_", " ")}</StatusLabel>) : <StatusLabel>No assigned role</StatusLabel>}</div></article><article className="rounded-2xl border border-white/10 bg-[var(--surface)] p-5"><p className="text-xs font-extrabold uppercase tracking-wider text-zinc-600">Age verification</p><div className="mt-3"><StatusLabel tone={state.ageVerified ? "positive" : "neutral"}>{state.ageVerified ? "Verified" : "Not verified"}</StatusLabel></div></article><article className="rounded-2xl border border-white/10 bg-[var(--surface)] p-5"><p className="text-xs font-extrabold uppercase tracking-wider text-zinc-600">Subscription</p><div className="mt-3"><StatusLabel tone={state.subscriptionActive ? "positive" : "neutral"}>{state.subscriptionActive ? "Active" : state.subscriptionStatus === "expired" ? "Expired" : "Inactive"}</StatusLabel></div></article></section>
    <div className="mt-8 flex flex-wrap gap-3"><Link href="/member" className="inline-flex min-h-11 items-center rounded-xl bg-fuchsia-500 px-5 text-sm font-extrabold text-white hover:bg-fuchsia-400">Check member access</Link><Link href="/" className="inline-flex min-h-11 items-center rounded-xl border border-white/15 px-5 text-sm font-extrabold text-white hover:bg-white/[0.05]">Public website</Link></div>
  </main>;
}
