"use client";

import { useActionState } from "react";
import { configureLiveAction, deleteLiveMessageAction, restrictLiveUserAction, setLiveStatusAction, type LiveActionState } from "@/app/mod/live/actions";
import type { LiveChatMessage, LiveSession } from "@/lib/live/model";

const initial: LiveActionState = { tone: "idle", message: "" };
function Feedback({ state }: { state: LiveActionState }) { return state.message ? <p role={state.tone === "error" ? "alert" : "status"} className={`mt-3 text-sm ${state.tone === "error" ? "text-rose-200" : "text-emerald-200"}`}>{state.message}</p> : null; }

export function LiveConfigurationForm({ session }: { session: LiveSession | null }) {
  const [state, action, pending] = useActionState(configureLiveAction.bind(null, session?.id ?? null, session?.updatedAt ?? null), initial);
  return <form action={action} className="space-y-4"><h2 className="font-display text-2xl font-bold text-white">Stream configuration</h2><label className="block text-sm text-zinc-300">Title<input name="title" defaultValue={session?.title ?? "Brandon Jamez Live"} maxLength={160} required className="mt-1 min-h-11 w-full border border-white/15 bg-black/30 px-3 text-white" /></label><label className="block text-sm text-zinc-300">Source<select name="source" defaultValue={session?.source ?? "youtube"} className="mt-1 min-h-11 w-full border border-white/15 bg-black px-3 text-white"><option value="youtube">YouTube</option><option value="direct">External direct playback</option></select></label><label className="block text-sm text-zinc-300">YouTube video ID<input name="youtubeVideoId" defaultValue={session?.youtubeVideoId ?? ""} maxLength={11} className="mt-1 min-h-11 w-full border border-white/15 bg-black/30 px-3 text-white" /></label><label className="block text-sm text-zinc-300">Direct provider key<input name="directPlaybackProvider" defaultValue={session?.directPlaybackProvider ?? ""} className="mt-1 min-h-11 w-full border border-white/15 bg-black/30 px-3 text-white" /></label><label className="block text-sm text-zinc-300">Opaque playback reference<input name="directPlaybackReference" defaultValue={session?.directPlaybackReference ?? ""} className="mt-1 min-h-11 w-full border border-white/15 bg-black/30 px-3 text-white" /></label><p className="text-xs leading-5 text-zinc-500">Never enter an ingest key, signed URL, manifest URL or secret. The reference is resolved by the future external-player adapter.</p><button disabled={pending} className="min-h-11 border border-white/15 px-4 font-bold text-white">Save configuration</button><Feedback state={state} /></form>;
}

export function LiveStatusForm({ session }: { session: LiveSession }) { const [state, action, pending] = useActionState(setLiveStatusAction.bind(null, session.id, session.updatedAt), initial); return <form action={action} className="mt-6 flex flex-wrap items-end gap-3"><label className="text-sm text-zinc-300">Status<select name="status" defaultValue={session.status} className="mt-1 block min-h-11 border border-white/15 bg-black px-3 text-white"><option value="offline">Offline</option><option value="scheduled">Scheduled</option><option value="live">Live</option><option value="ended">Ended</option></select></label><button disabled={pending} className="min-h-11 border border-white/15 px-4 font-bold text-white">Change status</button><Feedback state={state} /></form>; }

function MessageControls({ sessionId, message }: { sessionId: string; message: LiveChatMessage }) { const [deleteState, deleteAction, deleting] = useActionState(deleteLiveMessageAction.bind(null, message.id), initial); const [restrictState, restrictAction, restricting] = useActionState(restrictLiveUserAction.bind(null, sessionId, message.authorKey), initial); return <div className="mt-2 flex flex-wrap gap-2"><form action={deleteAction}><button disabled={deleting || message.status === "deleted"} className="border border-white/15 px-3 py-1 text-xs text-white">Remove</button></form><form action={restrictAction} className="flex gap-2"><input type="hidden" name="kind" value="timeout" /><select name="duration" defaultValue="300" className="border border-white/15 bg-black px-2 text-xs text-white"><option value="60">1 min</option><option value="300">5 min</option><option value="600">10 min</option><option value="3600">1 hour</option><option value="86400">24 hours</option></select><button disabled={restricting} className="border border-white/15 px-3 py-1 text-xs text-white">Timeout</button></form><form action={restrictAction}><input type="hidden" name="kind" value="ban" /><button disabled={restricting} className="border border-white/15 px-3 py-1 text-xs text-white">Ban</button></form><Feedback state={deleteState.tone !== "idle" ? deleteState : restrictState} /></div>; }

export function LiveChatModeration({ session, messages }: { session: LiveSession; messages: LiveChatMessage[] }) { return <section><h2 className="font-display text-2xl font-bold text-white">Website live chat</h2><div className="mt-4 max-h-[38rem] divide-y divide-white/10 overflow-y-auto">{messages.length ? messages.map((message) => <article key={message.id} className="py-4"><p className="text-sm text-zinc-300"><strong className="text-white">{message.authorDisplayName}</strong> {message.body}</p><MessageControls sessionId={session.id} message={message} /></article>) : <p className="py-4 text-sm text-zinc-500">No messages yet.</p>}</div></section>; }

